config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :posts do
    get 'current_user_posts', on: :collection
    get 'agenda', on: :collection
  end
  root 'posts#index'
  # match '*path' => redirect('/'), via: :get

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_rich_text :body
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 200 }, uniqueness: {case_sensitive: false}
  validates :body, presence: true, length: { maximum: 10000 }
  default_scope -> { order(created_at: :desc) }
  scope :active, -> { where(active: true).order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  validates :name, uniqueness: { case_sensitive: false }, presence: true, length: { in: 3..30 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  before_save { email.downcase! }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :add_current_user_to_post]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def current_user_posts
    @current_user_posts = current_user.posts
    # render json: @current_user_posts
      render json: { html: render_to_string(partial: 'current_user_posts') }
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @skip_header = true

     if @post.images.count > 0
      @first_post_image = rails_blob_url(@post.images.first)
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def agenda
  end

  private

    # Use callbacks to share common setup or constraints between actions.


    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :active, images: [])
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create

    super

  end

  # GET /resource/edit
  def edit
    super

  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name])
    # params.require(:user).permit(:name, :email, :password)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :name])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <%= fa_icon "fas twitter stack-2x" %>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <%= fa_icon "fas facebook stack-2x" %>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <%= fa_icon "fas github stack-2x" %>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="masthead" style="background-image: url('/images/about-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Test Blog</h1>
        <span class="subheading"></span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  </head>

  <body>
 <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to 'Agenda', agenda_posts_path, class: 'nav-link' %>
            </li>
          <% if user_signed_in? %>

            <li class="nav-item">
              <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <a class="nav-link no-hover", ref="">How dee, <%= current_user.name %>?</a>
            </li>

          <% else %>

            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
            </li>

          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <p class="navbar-text float-right">
  </p>

  <%= render "layouts/header" unless @skip_header %>

  <%= yield %>

  <%= render "layouts/footer" %>

  </body>
</html>

app/views/posts/_current_user_posts.html.erb
<% unless @current_user_posts.count > 0 %>
    <div class="col-md-12 text-center no-posts">
        There are no your posts yet.
    </div>
<% end %>

<div class="col-lg-8 col-md-10 mx-auto">
  <div class="buttons-block text-center">
    <% if user_signed_in? %>
      <%= link_to 'All Posts', posts_path,  id: "all_posts_button",  remote: true, onclick: "loadAllPosts('posts_path')", class: "btn btn-secondary" %>
      <%= link_to 'New Post', new_post_path, class: "btn btn-secondary" %>
    <% else %>
      <div class="col-md-12 text-center please-login-message hidden">
        Please, login to write new post.
      </div>
    <% end %>
  </div>

  <% @current_user_posts.each do |post| %>
    <div class="post-preview">
      <%= link_to post do %>
        <h2 class="post-title">
         <%= post.title %>
        </h2>
        <h3 class="post-subtitle">
          <% if post.active? %>
            <%= truncate(strip_tags(post.body.to_s), length: 150) %>
          <% else  %>
            Not pablished on home page
          <% end  %>
        </h3>
      <% end %>
      <div class="post-meta">
        <div class="row">
          <div class="col-md-6 text-left">
            Posted by <span class="author"><%= post.user.name %></span>
            <%= post.created_at.strftime("%Y-%m-%d") %>
          </div>

          <% if current_user && post.user_id == current_user.id %>
            <div  class="col-md-6 text-right icons">
              <%= link_to (fa_icon "fas eye"), post %>
              <%= link_to (fa_icon "fas edit"), edit_post_path(post) %>
              <%= link_to (fa_icon "fas trash"), post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          <% end %>
        </div>
      </div>
      <hr>
    </div>
  <% end %>

</div>

app/views/posts/_form.html.erb
<div class="container">

  <%= bootstrap_form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.rich_text_area :body %>
    </div>

    <div class="field">
      <%= form.file_field :images, multiple: true %>
    </div>

    <div class="field">
      <%= form.check_box :active %>
    </div>
    <br>

    <div class="actions">
      <%= form.submit %>
      <%= link_to 'Back', posts_path, class: "btn btn-secondary"  %>
    </div>

  <% end %>
</div>

app/views/posts/agenda.html.erb
<div class="container">

  <p>Создать блог</p>
  <p>Пользователь может:</p>
  <ol>
    <li>Aвторизироваться / регистрироваться /</li>
    <li>Создать / редактировать / удалять / делать невидимыми(не отображаемыми в списке постов) посты своего блога</li>
    <li>Смотреть список всех постов( как своих так и чужих, только те что видимы)</li>
    <li>Смотреть список своих постов</li>
  </ol>

  <p>Для стилей использовать bootstrap css</p>

</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="container">
    <div class="row">
      <div id="current_user_posts"></div>
      <div class="col-lg-8 col-md-10 mx-auto" id="all_posts">
        <% unless @posts.active.count > 0 %>
           <div class="col-md-12 text-center no-posts">
              There are no posts yet.
          </div>
        <% end %>

        <div class="buttons-block text-center">
          <% if user_signed_in? %>
            <%= link_to "#{current_user.name}'s POSTS", current_user_posts_posts_path, id: "current_user_posts_button",class: "btn btn-secondary", remote: true, onclick: "loadCurrentUserPosts()" %>

            <%= link_to 'New Post', new_post_path, class: "btn btn-secondary" %>
          <% else %>
            <div class="col-md-12 text-center please-login-message hidden">
              Please, login to write new post.
            </div>
          <% end %>
        </div>

        <% @posts.active.each do |post| %>
          <div class="post-preview">
            <%= link_to post do %>
              <h2 class="post-title">
               <%= post.title %>
              </h2>
              <h3 class="post-subtitle">
                <%= truncate(strip_tags(post.body.to_s), length: 150) %>
              </h3>
            <% end %>
            <div class="post-meta">
              <div class="row">
                <div class="col-md-6 text-left">
                  Posted by <span class="author"><%= post.user.name %></span>
                  <%= post.created_at.strftime("%Y-%m-%d") %>
                </div>

                <% if current_user && post.user_id == current_user.id %>
                  <div  class="col-md-6 text-right icons">
                    <%= link_to (fa_icon "fas eye"), post %>
                    <%= link_to (fa_icon "fas edit"), edit_post_path(post) %>
                    <%= link_to (fa_icon "fas trash"), post, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                <% end %>
              </div>
            </div>
            <hr>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<header class="masthead" style="background-image: url(<%= @first_post_image %>)">
  <div class="overlay"></div>
  <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1><%= @post.title %></h1>

              <span class="meta">Posted by
                <span class="author">
                  <%= @post.user.name %>
                </span>
                <%= @post.created_at.strftime("%Y-%m-%d") %>
              </span>

              <% unless @post.active? %>
                <br>
                <span class="meta">Not published on home page</span>
              <% end %>
          </div>
        </div>
      </div>
  </div>
</header>
  <p id="notice"><%= notice %></p>
  <% if current_user && @post.user_id == current_user.id %>
    <div class="text-center show-icons">
      <%= link_to (fa_icon "fas edit"), edit_post_path(@post) %>
      <%= link_to (fa_icon "fas trash"), @post, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>

  <article>
    <div class="container">

      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p><%= @post.body %></p>
        </div>
      </div>

      <hr>
      <div class="row">
        <% @post.images.each do |image| %>

        <div class="col-lg-4 col-md-4 col-xs-4 thumb post_show_image">
         <%= image_tag(image, :class => "img-responsive") %>
        </div>
      <% end %>

      </div>

    </div>
  </article>